Avoid scanning non-default partitions
keithf4/pg_partman pull request #662
Opened 2024-05-30 16:03 UTC by nicolagi

This is a minimal change to address #660.
It changes one query from selecting the max timestamp in a given partition (which may incur a full table scan) to selecting any timestamp (which should be fast).

**Testing.** I tested it with:

```
pg_prove -U $myuser -d $mydb -ovf test/*.sql
```

**Proof.** I'll argue that the query change does not change the behavior of the function.

Let P be the partition being iterated on.

If it's empty, then `v_max_timestamp` evaluates to null in both old and new code, and the loop iteration does nothing in both old and new code.

Let's then consider a non empty partition P.
Let A (for any timestamp) be the timestamp returned by the new code, and let M (for max) be that returned by the old code.
We have A <= M.

If A >= CURRENT_TIMESTAMP then `show_partition_name` gives back P for both old and new code. (Using A or M doesn't make a difference, as they're both in P.)

Let's look at the case when A < CURRENT_TIMESTAMP.
If also M < CURRENT_TIMESTAMP, both the old and the new code would use CURRENT_TIMESTAMP, so no difference.

It remans to consider the case

    A < CURRENT_TIMESTAMP <= M,

in which case CURRENT_TIMESTAMP still belongs to partition P, so the old code (uses M) and the new code (uses CURRENT_TIMESTAMP) both return P.

---

A nitpick would be that the variable `v_max_timestamp` should be renamed, perhaps `v_child_timestamp`, but I wanted to keep the change minimal.

2024-06-10 20:01 UTC, keithf4 commented
Thanks! Will take a look at this when I return to development.

2024-10-11 20:46 UTC, keithf4 requested changes

2024-10-11 20:46 UTC, keithf4 commented on sql/functions/run_maintenance.sql
> +            EXECUTE format('SELECT %s::text FROM %I.%I LIMIT 1'
Update the comments on lines 217 above and 241 below to be relevant that it's no longer getting the max value. Other than that, looks great! Thanks for the PR!

2024-10-15 14:53 UTC, nicolagi commented on sql/functions/run_maintenance.sql
> +            EXECUTE format('SELECT %s::text FROM %I.%I LIMIT 1'
Quite right, I attempted to explain the new version, feel free to edit!

2024-10-15 15:21 UTC, keithf4 commented on sql/functions/run_maintenance.sql
> +            EXECUTE format('SELECT %s::text FROM %I.%I LIMIT 1'
Looks. great. Thanks!

2024-10-15 15:22 UTC, keithf4 approved these changes

2024-10-15 15:22 UTC, merged